INSERT INTO test.milktea (id, name, des, price, type, type_name) VALUES ('0002', '红油小面', '经典芒芒与杨枝甘露的灵感碰撞，精选清幽绿妍茶底，爆汁红柚粒撞上大块芒肉。', 27, '1', '早餐');
INSERT INTO test.milktea (id, name, des, price, type, type_name) VALUES ('0003', '豆浆', '精选当季水蜜桃搭配金玉茶底制作而成，不使用任何香精等添加剂，不使用任何罐头水果。粉色为火龙果天然调色。若有小黑点，是火龙果籽，可放心食用。', 30, '1', '早餐');
INSERT INTO test.milktea (id, name, des, price, type, type_name) VALUES ('0004', '鸡腿饭', '精品定制绿茶，较普通绿茶，少了几分涩气，口感清澈，茉莉香气馥郁怡人。', 19, '2', '午餐');
INSERT INTO test.milktea (id, name, des, price, type, type_name) VALUES ('0005', '煲仔饭', '精品定制乌龙，清新茶香中带有桂花香和淡淡的乳香，馥郁迷人。', 22, '2', '午餐');
INSERT INTO test.milktea (id, name, des, price, type, type_name) VALUES ('0006', '钵钵鸡', '选用嫣红茶底。浓厚黄豆粉、芋圆波波搭配秘制豆乳奶盖，底部藏有滑嫩豆花。饮用秘籍：1.舀起顶部小丸子和豆奶盖先尝，2.吸管一插到底，再吸豆花与奶茶。', 27, '3', '夜宵');
INSERT INTO test.milktea (id, name, des, price, type, type_name) VALUES ('0007', '玉米汁', '本品含有芋头，过敏人士请谨慎选择。因芋泥容易氧化，为保持最佳体验，请务必于一小时内饮用完毕。新鲜芋泥融入顺滑冷藏牛乳，再加入颗颗Q弹的芋泥波波，绵密与润泽，尽在这一杯。', 27, '3', '夜宵');
INSERT INTO test.milktea (id, name, des, price, type, type_name) VALUES ('0008', '炸酱面', '意式奶咖与浓香芝士的默契结合，带来更浓郁的奶香。', 25, '4', '晚餐');
INSERT INTO test.milktea (id, name, des, price, type, type_name) VALUES ('0009', '鱼香肉丝', '香草牛奶拿铁与香草奶油雪顶灵感碰撞，佐以酥脆可口的碧根果碎，散发出柔和的坚果香及奶香。', 29, '4', '晚餐');
INSERT INTO test.milktea (id, name, des, price, type, type_name) VALUES ('0010', '煎饺', '选用定制草莓搭配清幽绿妍茶底新鲜现制，莓香满溢。如选择甜菊糖，遇酸性水果会产生泡沫，属正常现象。', 32, '1', '早餐');
INSERT INTO test.milktea (id, name, des, price, type, type_name) VALUES ('0011', '馒头', '莓莓与桃桃的首次灵感混搭。莓莓沁入桃汁，搭配清雅绿妍与浓醇芝士，一次喝到两款人气饮品。', 31, '1', '早餐');
INSERT INTO test.milktea (id, name, des, price, type, type_name) VALUES ('0012', '包子', '精选饱满红柚果粒入茶，清幽绿妍茶底洋溢茉莉花香。冰沙减少了红柚的微苦，更凸显茶味。如选择甜菊糖，遇酸性水果会产生泡沫，属正常现象。', 25, '1', '早餐');
INSERT INTO test.milktea (id, name, des, price, type, type_name) VALUES ('0013', '麻婆豆腐', '精品定制乌龙茶，香气碳焙浓郁，入喉回甘，茶香余韵不断。', 22, '2', '午餐');
INSERT INTO test.milktea (id, name, des, price, type, type_name) VALUES ('0014', '肉夹馍', '黑糖珍珠搭配顺滑冷藏牛乳。波波系列奶味较为浓郁，不喜欢浓厚口感的朋友慎点。', 21, '3', '夜宵');
INSERT INTO test.milktea (id, name, des, price, type, type_name) VALUES ('0015', '臭豆腐', '软糯可口的芝麻汤圆串串，搭配秘制豆豆奶盖和焙香芝麻粉更好味，黑芝麻奶底藏有芋圆波波，团圆芝喜，尽在一杯。', 27, '3', '夜宵');
INSERT INTO test.milktea (id, name, des, price, type, type_name) VALUES ('0016', '炒面', '经典奶茶回归，嫣红茶搭配牛乳打制细腻冰沙，黑糖波波和冰淇淋球的组合让口感层次更加丰富。', 27, '3', '夜宵');
INSERT INTO test.milktea (id, name, des, price, type, type_name) VALUES ('0017', '毛血旺', '精品咖啡豆现磨萃出可可香气，加入谷物麦片搭配黄金椰片与香草奶油顶，口齿萦绕愉悦椰香，能量咖啡就这杯。', 28, '4', '晚餐');
INSERT INTO test.milktea (id, name, des, price, type, type_name) VALUES ('0018', '狮子头', '选用优质阿拉比卡咖啡豆拼配，现萃咖啡融入蒸煮牛奶，呈现经典拿铁的香纯。', 19, '4', '晚餐');
INSERT INTO test.milktea (id, name, des, price, type, type_name) VALUES ('0019', '酱大排', '现萃Espresso沁入细密冰沙，佐以Q弹黑糖波波，混搭出新格调。', 25, '4', '晚餐');
INSERT INTO test.milktea (id, name, des, price, type, type_name) VALUES ('0020', '剁椒鱼头', '选用优质阿拉比卡咖啡豆拼配，原豆现磨，冲泡出纯粹饱满的咖啡香气。', 13, '4', '晚餐');
INSERT INTO test.milktea (id, name, des, price, type, type_name) VALUES ('0021', '小龙虾', '当香浓醇厚的浓缩咖啡遇上清爽酸甜的柠檬滋味，给您带来与众不同夏日咖啡感受。', 16, '4', '晚餐');
INSERT INTO test.milktea (id, name, des, price, type, type_name) VALUES ('0022', '紫菜蛋花汤', '选用进口淡奶油制成绵密乳霜，加入醇香的现磨咖啡，香浓绵滑多层次的口感，融合在味蕾中的幸福感受。', 17, '4', '晚餐');
INSERT INTO test.milktea (id, name, des, price, type, type_name) VALUES ('0001', '烧麦', '当季巨峰葡萄回归，颗颗手剥，保留果肉完整口感。搭配清雅绿妍茶底与醇香芝士，鲜爽可口。如选择甜菊糖，遇酸性水果会产生泡沫，属正常现象。
', 29, '1', '早餐');
